# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='title',
            field=models.CharField(default='untitled', max_length=30, null=True),
        ),
    ]
