# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='student',
            new_name='participant',
        ),
    ]
