# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='emailtrue',
        ),
        migrations.AlterField(
            model_name='user',
            name='credit',
            field=models.CharField(max_length=10),
        ),
    ]
