# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writing',
            name='corrector',
        ),
    ]
