# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coment', models.CharField(max_length=10000)),
                ('email', models.CharField(max_length=100)),
                ('page', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='writing',
            name='corrector',
            field=models.CharField(default='noOne', max_length=10),
        ),
    ]
