# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-21 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20161219_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='text',
            field=models.TextField(max_length=10000),
        ),
    ]
