# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-21 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20161221_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
