# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 06:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20170220_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student_id',
        ),
        migrations.AddField(
            model_name='course',
            name='student_id',
            field=models.ManyToManyField(through='user_profile.Registration', to=settings.AUTH_USER_MODEL),
        ),
    ]
