# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_user_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
