# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-16 06:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
