# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-16 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20161216_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='wallet',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
