# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20170220_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='student_id',
            new_name='student',
        ),
    ]
