# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20170220_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
