# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-28 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20161228_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='title',
            field=models.CharField(default='untitled', max_length=30),
        ),
    ]
