# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-01 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20170101_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='tpo',
            field=models.BooleanField(default=True),
        ),
    ]
