# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-01 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_subject_tpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='title',
            field=models.CharField(default='untitled', max_length=3000),
        ),
    ]
