# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-08 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_auto_20170101_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='grammer',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='writing',
            name='oad',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='writing',
            name='unity',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='writing',
            name='vocab',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='writing',
            name='wordchoice',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
