# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-10 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_writing_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='adresssc',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='writing',
            name='grammersc',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='writing',
            name='oadsc',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='writing',
            name='unitysc',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='writing',
            name='vocabsc',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='writing',
            name='wordchoicesc',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
