# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 13:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_auto_20170110_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacherate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherscore', to=settings.AUTH_USER_MODEL)),
                ('writing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Writing')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
