# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='wallet',
            field=models.CharField(max_length=2),
        ),
    ]
