# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 12:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0019_credit_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='credit',
            name='number2',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='credit',
            name='number3',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='credit',
            name='wallet2',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='credit',
            name='wallet3',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
