# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0020_auto_20170123_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=100)),
                ('number', models.CharField(default=0, max_length=100)),
                ('wallet2', models.CharField(default=0, max_length=100)),
                ('number2', models.CharField(default=0, max_length=100)),
                ('wallet3', models.CharField(default=0, max_length=100)),
                ('number3', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Credit',
        ),
    ]
