# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0021_auto_20170123_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amount2',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='credit2',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
