# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0022_auto_20170201_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='authority',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
