# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-02 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0026_auto_20170201_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='buy',
            name='authority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buy',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='price',
            name='number2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='price',
            name='number3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='price',
            name='wallet',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='wallet2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='price',
            name='wallet3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacherate',
            name='rate',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='writing',
            name='adresssc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='writing',
            name='grammersc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='writing',
            name='oadsc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='writing',
            name='score',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='writing',
            name='unitysc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='writing',
            name='vocabsc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='writing',
            name='wordchoicesc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
