# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-18 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0027_auto_20170202_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherate',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='writing',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
