# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-18 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0028_auto_20170218_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writing',
            name='corrector',
        ),
    ]
