# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-18 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0030_writing_corrector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writing',
            old_name='corrector',
            new_name='correctiiir',
        ),
    ]
