# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-18 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0031_auto_20170218_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writing',
            old_name='correctiiir',
            new_name='corrector',
        ),
    ]
