# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0034_event_hamayesh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamayesh',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='hamayesh',
            name='grade',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='hamayesh',
            name='major',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='hamayesh',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
    ]
