# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corrector', '0001_initial'),
        ('user_profile', '0002_remove_writing_corrector'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Corrector',
        ),
    ]
