# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-08 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corrector', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Corrector',
        ),
    ]
